# (11주차) 11월18일
> 체인룰

- toc:true
- branch: master
- badges: true
- comments: true
- author: 최규빈

### 강의영상 

> youtube: https://youtube.com/playlist?list=PLQqh36zP38-wC6aKJkQrtjg8h-PzhILkn

`-` (1/4) 체인룰을 이용한 미분계수 계산, 이론 (1) 

`-` (2/4) 체인룰을 이용한 미분계수 계산, 이론 (2) 

`-` (3/4) 체인룰을 이용한 미분계수 계산, 실습

`-` (4/4) 과제설명

### import 

In [1]:
import torch 

### 지난시간 복습 

`-` 회귀분석에서 손실함수에 대한 미분은 아래와 같은 과정으로 계산할 수 있다. 

- $loss = ({\bf y}-{\bf X}{\bf W})^\top ({\bf y}-{\bf X}{\bf W})={\bf y}^\top {\bf y} - {\bf y}^\top {\bf X}{\bf W} - {\bf W}^\top {\bf X}^\top {\bf y} + {\bf W}^\top {\bf X}^\top {\bf X} {\bf W}$

- $\frac{\partial }{\partial {\bf W}}loss = -2{\bf X}^\top {\bf y} +2 {\bf X}^\top {\bf X} {\bf W}$

### 오늘수업의 목표 

`-` 목표: 미분을 계산할 수 있는 컴퓨터(core)가 여러개 있다고 할때, 위의 계산을 더 빠르게 할 방법이 있을까? 
- 체인룰 $\to$ 역전파기법 (backpropagation) 

`-` 어떻게 하면 미분계산을 여러 컴퓨터에게 적당히 나누어 수행시킬 수 있을까? 

### 체인룰 (어려운 하나의 미분을 손쉬운 여러개의 미분으로 나누는 기법) 

`-` 손실함수가 사실 아래와 같은 변환을 거쳐서 계산되었다고 볼 수 있다. 

- ${\bf X} \to {\bf X}{\bf W} \to {\bf y} -{\bf X}{\bf W} \to ({\bf y}-{\bf X}{\bf W})^\top ({\bf y}-{\bf X}{\bf W})$

`-` 위의 과정을 수식으로 정리해보면 아래와 같다. 

- ${\bf u}={\bf X}{\bf W}$, $\quad {\bf u}: n \times 1$ 

- ${\bf v} = {\bf y}- {\bf u},$  $\quad {\bf v}: n \times 1$

- $loss={\bf v}^\top {\bf v},$ $\quad loss: 1 \times 1 $

`-` 손실함수에 대한 미분은 아래와 같다. 

$$\frac{\partial }{\partial {\bf W}} loss = \frac{\partial }{\partial {\bf W}} {\bf v}^\top {\bf v} $$ 

(그런데 이걸 어떻게 계산함?)

`-` 계산할 수 있는것들의 모음.. 

- $\frac{\partial}{\partial {\bf v}} loss = 2{\bf v} $ $\quad \to$ (n,1) 벡터 

- $\frac{\partial }{\partial {\bf u}} {\bf v}^\top = -{\bf I}$ $\quad \to $ (n,n) 매트릭스 

- $\frac{\partial }{\partial \bf W}{\bf u}^\top = {\bf X}^\top $ $\quad \to$ (p,n) 매트릭스 

`-` 혹시.. 아래와 같이 쓸 수 있을까?  

$$ \left(\frac{\partial }{\partial \bf W}{\bf u}^\top \right) 
\left(\frac{\partial }{\partial \bf u}{\bf v}^\top \right) 
\left(\frac{\partial }{\partial \bf v}loss \right) = 
\frac{\partial {\bf u}^\top}{\partial \bf W}
\frac{\partial {\bf v}^\top}{\partial \bf u}
\frac{\partial loss}{\partial \bf v}
$$ 

- 가능할것 같다. 뭐 기호야 정의하기 나름이니까!

`-` 그렇다면 혹시 아래와 같이 쓸 수 있을까? 

$$
\frac{\partial {\bf u}^\top}{\partial \bf W}
\frac{\partial {\bf v}^\top}{\partial \bf u}
\frac{\partial loss}{\partial \bf v} = \frac{\partial loss }{\partial\bf W}=\frac{\partial }{\partial \bf W} loss
$$

- 이건 선을 넘는 것임.
- 그런데 어떠한 공식에 의해서 가능함. 그 공식 이름이 체인룰이다. 

`-` 결국 정리하면 아래의 꼴이 되었다. 

$$\left(\frac{\partial }{\partial \bf W}{\bf u}^\top \right) 
\left(\frac{\partial }{\partial \bf u}{\bf v}^\top \right) 
\left(\frac{\partial }{\partial \bf v}loss \right) 
= 
\frac{\partial }{\partial \bf W}loss $$ 

`-` 그렇다면? 

$$\left({\bf X}^\top  \right) 
\left(-{\bf I} \right) 
\left(2{\bf v}\right) 
= 
\frac{\partial }{\partial \bf W}loss $$ 

그런데, ${\bf v}={\bf y}-{\bf u}={\bf y} -{\bf X}{\bf W}$ 이므로 

$$-2{\bf X}^\top\left({\bf y}-{\bf X}{\bf W}\right) 
= 
\frac{\partial }{\partial \bf W}loss $$ 

정리하면 

$$\frac{\partial }{\partial \bf W}loss = -2{\bf X}^\top{\bf y}+2{\bf X}^\top {\bf X}{\bf W}$$ 

### 예시: 중간고사 문제.. 

`-` 미분계수를 계산하는 문제였음.. 

`-` 체인룰을 이용하여 미분계수를 계산하여 보자.

In [30]:
ones= torch.ones(5)
x = torch.tensor([11.0,12.0,13.0,14.0,15.0])
X = torch.vstack([ones,x]).T
y = torch.tensor([17.7,18.5,21.2,23.6,24.2])

In [31]:
W = torch.tensor([3.0,3.0]) 

In [32]:
u = X@W 
v = y-u 
loss = v.T @ v 

In [33]:
loss

tensor(2212.1799)

`-` $\frac{\partial}{\partial\bf W}loss $ 의 계산 

In [22]:
X.T @ -torch.eye(5) @ (2*v) 

tensor([ 209.6000, 2748.6001])

`-` 참고로 중간고사 답은 

In [13]:
X.T @ -torch.eye(5)@ (2*v) / 5 

tensor([ 41.9200, 549.7200])

입니다. 

`-` 확인 

In [16]:
_W = torch.tensor([3.0,3.0],requires_grad=True) 

In [19]:
_loss = (y-X@_W).T @ (y-X@_W)

In [20]:
_loss.backward()

In [21]:
_W.grad.data

tensor([ 209.6000, 2748.6001])

### 숙제 

`-` $\frac{\partial}{\partial \bf v} loss= 2{\bf v}$ 임을 확인하라. 

In [38]:
v

tensor([-18.3000, -20.5000, -20.8000, -21.4000, -23.8000])

In [39]:
_v= torch.tensor([-18.3000, -20.5000, -20.8000, -21.4000, -23.8000],requires_grad=True)

In [40]:
_loss = _v.T @ _v 

In [41]:
_loss.backward() 

In [ ]:
_v.grad.data, v 